### ISSUE TITLE
Intermittent launch failures: WebKit Threading Violation - initial use of WebKit from a secondary thread.

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios-server#218]
Only seeing this in Calabash 2.0 at the moment with the CocoaHTTPServer 2.3 sources.

Xcode 6.4

```
 Time out waiting for UIAutomation run-loop execution expired. 
  Logfile /var/folders/bx/5wplnzxx7492fynry0m_hw080000gp/T/run_loop20150720-60743-5tcdlw/run_loop.out 
 
  2015-07-20 21:23:54.441 instruments[64395:402028] WebKit Threading Violation - initial use of WebKit from a secondary thread.
 
  (RunLoop::TimeoutError)
 /Users/moody/git/calabash/calabash/lib/calabash/ios/device/device.rb:402:in `start_app_with_device_and_options'
 /Users/moody/git/calabash/calabash/lib/calabash/ios/device/device.rb:369:in `start_app_on_simulator'
 /Users/moody/git/calabash/calabash/lib/calabash/ios/device/device.rb:350:in `_start_app'
 /Users/moody/git/calabash/calabash/lib/calabash/device.rb:37:in `start_app'
 /Users/moody/git/calabash/calabash/lib/calabash/life_cycle.rb:10:in `start_app'
```

Log file contains one line:

```
instruments[64395:402028] WebKit Threading Violation - initial use of WebKit from a secondary thread.
```

I see this output a bunch in the Terminal, but it has never caused problems.  Apple themselves told me this was "normal output".  This is the first time I have seen it cause the app not to launch.

@krukow @sapieneptus Please keep an eye out for this.

**Comment by hoangvm** [comment]
@jmoody 
I have same this problem,too.
Do you have any solution for this bug?
Did you solve it?

**Comment by hoangvm** [comment]
@jmoody 
I can run normally with Simulator. 
But does not work on Real Device Ipad (8.3)

**Comment by aluzardo** [comment]
Same problem here.

```
➜  ~ /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/ios/appium-instruments/instrumentscli0.trace -w 39d39a8bf0d6635268e5997dae574c04246f5e2b com.bytearc.SafariLauncher -e UIASCRIPT "/Users/adolfocabrera/Library/Application Support/appium/bootstrap/bootstrap-1f95f319c723b673.js" -e UIARESULTSPATH /tmp/ios/appium-instruments
2016-07-12 14:49:41.348 instruments[5037:1555723] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Instruments Usage Error: Specified target process is invalid: com.bytearc.SafariLauncher
instruments, version 7.3 (60134)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
```

How can I fix it?

**Comment by jmoody** [comment]
> WebKit Threading Violation - initial use of WebKit from a secondary thread.

This is output is normal according to Apple.

You have supplied the wrong arguments to `instruments`.  This appears to be output from Appium and not related to a Calabash run.

**Comment by aluzardo** [comment]
Sorry you are right I post in the wrong github repository. The problem is related to Appium.
